window.MASTER_PROFILE = {
  productName: "SlotBot",
  defaultLanguage: "ru",
  supportedLanguages: [
    { code: "sr", label: "SR" },
    { code: "en", label: "EN" },
    { code: "ru", label: "RU" },
  ],
  bookingUrl: "https://t.me/Beauty_Master_name_bot",
  telegramUrl: "https://t.me/Beauty_Master_name_bot",
  contactUrl: "https://t.me/jxx15",
  creatorName: "Created by Dun4ev",
  creatorUrl: "https://t.me/jxx15",
  whatsappUrl: "https://wa.me/381601234567",
  instagramUrl: "https://www.instagram.com/",
  portfolioUrl: "https://ru.pinterest.com/search/pins/?q=nail%20design&rs=typed",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Bulevar%20oslobodjenja%20119%2C%2021000%2C%20Novi%20Sad%2C%20Serbia",
  mapEmbedUrl:
    "https://maps.google.com/maps?q=Bulevar%20oslobodjenja%20119%2C%2021000%2C%20Novi%20Sad%2C%20Serbia&output=embed",
  demoVideo: "./assets/demo-poster.mp4",
  demoPoster: "./assets/demo-poster.jpg",
  nicheShowcaseImage: "./assets/demo-niches-showcase.png",
  demoImages: [
    "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=560&q=85",
    "https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=560&q=85",
    "https://images.unsplash.com/photo-1610992015762-45dca7fa50d4?auto=format&fit=crop&w=560&q=85",
    "https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=560&q=85",
  ],
  i18n: {
    ru: {
      title: "SlotBot | Telegram-бот для записи клиентов",
      metaDescription:
        "Демо продукта: Telegram booking bot + mini landing page для сервисного бизнеса. Запись клиентов, свободные слоты, уведомления и мини-сайт.",
      botFeatures: "Функции бота",
      featureBack: "Назад к лендингу",
      featureBadgeBot: "Booking bot",
      featureBadgeWebsite: "Landing page",
      featureBadgeSetup: "Custom setup",
      featureHeroTitle: "Что можно добавить в бот и лендинг",
      featureHeroText:
        "Базовый пакет быстро запускает запись клиентов. Дополнительные функции подключаются под процесс конкретного бизнеса.",
      featureDemoTitle: "Демо записи",
      featureDemoSubtitle: "Сценарий можно адаптировать под любую нишу",
      demoVideoTitle: "Демо-видео",
      demoVideoText: "Короткий ролик продукта",
      upgradeTitle: "Возможности расширения",
      upgradeSubtitle: "Выбирайте только то, что нужно бизнесу",
      packageTitle: "Как использовать демо",
      packageText:
        "Покажите текущий сценарий, выберите нужные блоки, а затем адаптируйте тексты, услуги, дизайн и логику записи.",
      discussCustom: "Обсудить внедрение",
      footerNote:
        "SlotBot - пример пакета: Telegram booking bot + landing page. Дизайн и сценарий адаптируются под нишу.",
      nav: {
        features: "Возможности",
        how: "Как работает",
        useCases: "Для кого",
        pricing: "Цены",
        faq: "FAQ",
      },
      sectionTitles: {
        clientBenefits: "Что получает клиент",
        workflow: "Как это работает",
        ownerBenefits: "Почему это полезно владельцу",
        useCases: "Подходит для",
        businessFeatures: "Функции для бизнеса",
      },
      hero: {
        badge: "Демо-кейс: nail master booking",
        title:
          "Telegram-бот для записи клиентов + мини-сайт для привлечения заявок",
        text:
          "Клиент видит услуги, цены и свободные слоты, а затем записывается через Telegram. Подходит не только для nail-мастера, но и для любого бизнеса с записью по времени или бронированием мест.",
        primaryCta: "Попробовать демо в Telegram",
        secondaryCta: "Для владельцев бизнеса",
        trust: ["RU / EN / SR", "Уведомления", "Напоминания", "Мессенджеры"],
      },
      clientBenefits: [
        {
          icon: "tag",
          title: "Услуги и цены",
          text: "Все понятно: что есть и сколько стоит.",
        },
        {
          icon: "calendar-days",
          title: "Свободные слоты",
          text: "Видит реальные окна и выбирает удобное.",
        },
        {
          icon: "zap",
          title: "Запись за 1 минуту",
          text: "Быстрый выбор и подтверждение без лишних шагов.",
        },
        {
          icon: "bell",
          title: "Напоминание о визите",
          text: "Не забудет о записи - получит напоминание заранее.",
        },
      ],
      workflowSteps: [
        "Человек заходит на лендинг",
        "Нажимает записаться",
        "Переходит в Telegram-бот",
        "Выбирает услугу, дату и время",
      ],
      workflowNote:
        "Мастер или администратор получает новую запись без ручной переписки.",
      videoDemo: {
        title: "Видео-демонстрация",
        text:
          "Покажите клиенту или владельцу бизнеса, как выглядит путь от лендинга до записи в Telegram.",
        fallback: "Если видео не загрузилось, проверьте путь к mp4 в config.js.",
      },
      ownerBenefits: [
        {
          icon: "messages-square",
          title: "Меньше ручной переписки",
          text: "Вся запись автоматизирована в Telegram.",
        },
        {
          icon: "inbox",
          title: "Меньше пропущенных заявок",
          text: "Не теряете клиентов из-за задержек.",
        },
        {
          icon: "calendar-check",
          title: "Понятное расписание",
          text: "Все записи в одном месте, без путаницы.",
        },
        {
          icon: "bell-ring",
          title: "Напоминания клиентам",
          text: "Меньше опозданий и неявок.",
        },
        {
          icon: "heart",
          title: "Возврат клиентов",
          text: "Удобно записываться снова - клиенты возвращаются.",
        },
        {
          icon: "paintbrush",
          title: "Кастомизация под нишу",
          text: "Адаптируем бота и сайт под ваш бизнес и стиль.",
        },
      ],
      useCases: [
        "Мастер маникюра",
        "Барбер",
        "Массаж",
        "Косметология",
        "Йога и занятия",
        "Мастер-классы",
        "Небольшие события",
        "Клиники",
        "Зубной врач",
        "Автосервис",
      ],
      useCasesNote: "Ногти - только один из примеров использования.",
      nicheShowcase: {
        badge: "Демо-обертки",
        title: "Один бот. Разные бизнесы.",
        text:
          "Логика записи остается общей, а витрина меняется под нишу: услуги, цены, адрес, фото, язык и тексты.",
        imageAlt:
          "Витрина демо-ниш SlotBot: Telegram-бот и мини-лендинги для разных сервисных бизнесов",
        cta: "Смотреть демо",
        soon: "Скоро",
        demos: [
          { title: "Beauty / Nail", href: "./demo/beauty/index.html", status: "ready" },
          { title: "Barber", href: "./demo/barber/index.html", status: "ready" },
          { title: "Massage", href: "./demo/massage/index.html", status: "ready" },
          { title: "Classes", href: "./demo/classes/index.html", status: "ready" },
          { title: "Events", href: "./demo/events/index.html", status: "ready" },
          { title: "Clinic", href: "./demo/clinic/index.html", status: "ready" },
          { title: "Dentist", href: "./demo/dentist/index.html", status: "ready" },
          { title: "Car Service", href: "./demo/car-service/index.html", status: "ready" },
        ],
      },
      demoCase: {
        title: "Пример применения: сайт мастера маникюра",
        name: "Anna • Nail Master",
        intro: "Идеальный маникюр для уверенности в себе",
        badge: "Beauty / Nail demo",
        openPageCta: "Открыть демо-страницу",
        bookCta: "Записаться",
        servicesTitle: "Услуги и цены",
        reviewsTitle: "Отзывы клиентов",
        locationTitle: "Где я работаю",
        review: "Очень довольна! Аккуратно, красиво и быстро. Обязательно приду еще!",
        location: "Белград, Сербия",
        services: [
          { name: "Маникюр классический", price: "1 800 RSD" },
          { name: "Маникюр + гель-лак", price: "2 300 RSD" },
          { name: "Укрепление ногтей", price: "500 RSD" },
          { name: "Дизайн ногтей", price: "от 200 RSD" },
        ],
        checklistTitle: "В демо-кейс входит:",
        checklist: [
          "Портфолио",
          "Услуги и цены",
          "Карта",
          "Кнопка записи",
          "Связь через WhatsApp / Instagram / Telegram",
        ],
        calloutTitle: "Этот сценарий легко адаптируется под другую нишу",
        calloutText: "Изменим дизайн, услуги и тексты под ваш бизнес.",
      },
      featureGroups: [
        {
          icon: "calendar-days",
          title: "Сценарий записи",
          text: "Путь клиента от выбора услуги до подтверждения.",
          items: ["выбор услуги", "дата и время", "подтверждение", "напоминания"],
        },
        {
          icon: "user-round",
          title: "Админ-панель",
          text: "Управление записью и клиентами для владельца.",
          items: ["уведомления", "список записей", "перенос и отмена", "управление клиентами"],
        },
        {
          icon: "megaphone",
          title: "Маркетинг",
          text: "Инструменты, которые помогают возвращать клиентов.",
          items: ["промокоды", "рассылки", "свободные окна", "акции и спецпредложения"],
        },
        {
          icon: "globe-2",
          title: "Лендинг",
          text: "Мини-сайт для трафика, доверия и заявки.",
          items: ["портфолио", "отзывы", "карта и контакты", "аналитика"],
        },
      ],
      demoSteps: [
        { title: "Выберите услугу", text: "Клиент начинает с понятного списка услуг.", image: "" },
        { title: "Выберите дату", text: "Показываются только доступные дни и окна.", image: "" },
        { title: "Подтверждение", text: "Админ получает заявку, клиент - напоминание.", image: "" },
      ],
      cta: {
        title: "Нужен такой же бот и лендинг под ваш бизнес?",
        text: "Сделаем базовую версию быстро, а затем расширим под ваш процесс.",
        discuss: "Обсудить проект",
        watch: "Смотреть демо",
      },
      pricingBlock: {
        title: "Цены",
        text:
          "Стоимость зависит от ниши, языков, дизайна и нужной логики записи. Базовый пакет можно обсудить в Telegram.",
      },
      faqBlock: {
        title: "FAQ",
        items: [
          {
            question: "Нужен ли backend для лендинга?",
            answer: "Нет. Лендинг остается статическим и может жить на GitHub Pages.",
          },
          {
            question: "Можно ли заменить nail-кейс?",
            answer:
              "Да. Услуги, тексты, визуальный стиль и сценарий записи меняются под вашу нишу.",
          },
        ],
      },
      footer: {
        subtitle: "Telegram booking bot + landing page",
        contacts: { telegram: "Telegram: @jxx15", location: "Белград, Сербия" },
        copyright: "© 2026 SlotBot. Все права защищены.",
        columns: [
          { title: "Продукт", links: ["Возможности", "Как работает", "Цены", "Демо"] },
          { title: "Компания", links: ["О нас", "Кейсы", "Блог", "Контакты"] },
          { title: "Поддержка", links: ["FAQ", "Документация", "Связаться с нами"] },
        ],
      },
      mockup: {
        phoneTitle: "SlotBot",
        stepLabel: "Шаг",
        flow: ["Выберите услугу", "Выберите дату", "Выберите время", "Подтверждение записи"],
        landingLabel: "Лендинг + бот",
        landingCta: "Записаться онлайн",
        map: "Карта рядом с контактами",
      },
    },
    en: {
      title: "SlotBot | Telegram booking bot",
      metaDescription:
        "Product demo: Telegram booking bot + mini landing page for service businesses.",
      botFeatures: "Bot features",
      featureBack: "Back to landing",
      featureBadgeBot: "Booking bot",
      featureBadgeWebsite: "Landing page",
      featureBadgeSetup: "Custom setup",
      featureHeroTitle: "What can be added to the bot and landing",
      featureHeroText:
        "The base package launches client booking quickly. Extra features are added around a real business workflow.",
      featureDemoTitle: "Booking demo",
      featureDemoSubtitle: "The scenario can be adapted to any niche",
      demoVideoTitle: "Demo video",
      demoVideoText: "Short product video",
      upgradeTitle: "Upgrade options",
      upgradeSubtitle: "Choose only what the business needs",
      packageTitle: "How to use this demo",
      packageText:
        "Show the current flow, choose useful blocks, then adapt texts, services, design and booking logic.",
      discussCustom: "Discuss setup",
      footerNote:
        "SlotBot is a package example: Telegram booking bot + landing page. Design and flow are adapted by niche.",
      nav: { features: "Features", how: "How it works", useCases: "For whom", pricing: "Pricing", faq: "FAQ" },
      sectionTitles: {
        clientBenefits: "What clients get",
        workflow: "How it works",
        ownerBenefits: "Why owners benefit",
        useCases: "Good fit for",
        businessFeatures: "Business features",
      },
      hero: {
        badge: "Demo case: nail master booking",
        title: "Telegram booking bot + mini landing page for client requests",
        text:
          "Clients see services, prices and available slots, then book through Telegram. Works for nail masters and any service business with time slots or seats.",
        primaryCta: "Try Telegram demo",
        secondaryCta: "For business owners",
        trust: ["RU / EN / SR", "Notifications", "Reminders", "Messengers"],
      },
      clientBenefits: [
        { icon: "tag", title: "Services and prices", text: "Clear offer and transparent pricing." },
        { icon: "calendar-days", title: "Available slots", text: "Clients choose from real open windows." },
        { icon: "zap", title: "Booking in 1 minute", text: "Fast selection and confirmation." },
        { icon: "bell", title: "Visit reminder", text: "Clients get a reminder before the visit." },
      ],
      workflowSteps: ["Visitor opens landing", "Clicks book", "Moves to Telegram bot", "Chooses service, date and time"],
      workflowNote: "The owner or admin receives a new booking without manual messaging.",
      videoDemo: {
        title: "Video demo",
        text:
          "Show clients or business owners how the flow looks from landing page to Telegram booking.",
        fallback: "If the video does not load, check the mp4 path in config.js.",
      },
      ownerBenefits: [
        { icon: "messages-square", title: "Less manual chat", text: "Booking is automated in Telegram." },
        { icon: "inbox", title: "Fewer missed leads", text: "Clients are not lost while waiting." },
        { icon: "calendar-check", title: "Clear schedule", text: "Bookings stay in one place." },
        { icon: "bell-ring", title: "Client reminders", text: "Fewer late arrivals and no-shows." },
        { icon: "heart", title: "Repeat visits", text: "Easy rebooking helps clients return." },
        { icon: "paintbrush", title: "Niche customization", text: "Bot and site match your process and style." },
      ],
      useCases: ["Nail master", "Barber", "Massage", "Cosmetology", "Yoga and classes", "Workshops", "Small events", "Clinics", "Dentist", "Auto service"],
      useCasesNote: "Nails are just one example use case.",
      nicheShowcase: {
        badge: "Demo wrappers",
        title: "One bot. Different businesses.",
        text:
          "The booking logic stays the same, while the landing wrapper changes by niche: services, prices, address, photos, language and copy.",
        imageAlt:
          "SlotBot demo niche showcase: Telegram bot and mini landing pages for different service businesses",
        cta: "View demo",
        soon: "Soon",
        demos: [
          { title: "Beauty / Nail", href: "./demo/beauty/index.html", status: "ready" },
          { title: "Barber", href: "./demo/barber/index.html", status: "ready" },
          { title: "Massage", href: "./demo/massage/index.html", status: "ready" },
          { title: "Classes", href: "./demo/classes/index.html", status: "ready" },
          { title: "Events", href: "./demo/events/index.html", status: "ready" },
          { title: "Clinic", href: "./demo/clinic/index.html", status: "ready" },
          { title: "Dentist", href: "./demo/dentist/index.html", status: "ready" },
          { title: "Car Service", href: "./demo/car-service/index.html", status: "ready" },
        ],
      },
      demoCase: {
        title: "Example use case: nail master website",
        name: "Anna • Nail Master",
        intro: "Perfect manicure for everyday confidence",
        badge: "Beauty / Nail demo",
        openPageCta: "Open demo page",
        bookCta: "Book",
        servicesTitle: "Services and prices",
        reviewsTitle: "Client reviews",
        locationTitle: "Where I work",
        review: "Very happy! Neat, beautiful and fast. I will definitely come again.",
        location: "Belgrade, Serbia",
        services: [
          { name: "Classic manicure", price: "1 800 RSD" },
          { name: "Manicure + gel polish", price: "2 300 RSD" },
          { name: "Nail strengthening", price: "500 RSD" },
          { name: "Nail design", price: "from 200 RSD" },
        ],
        checklistTitle: "Demo case includes:",
        checklist: ["Portfolio", "Services and prices", "Map", "Booking button", "WhatsApp / Instagram / Telegram contact"],
        calloutTitle: "This scenario is easy to adapt to another niche",
        calloutText: "We change design, services and texts for your business.",
      },
      featureGroups: [
        { icon: "calendar-days", title: "Booking Flow", text: "Client path from service to confirmation.", items: ["service selection", "date and time", "confirmation", "reminders"] },
        { icon: "user-round", title: "Admin", text: "Booking and client management.", items: ["notifications", "booking list", "reschedule and cancel", "client management"] },
        { icon: "megaphone", title: "Marketing", text: "Tools that help bring clients back.", items: ["promo codes", "broadcasts", "free windows", "special offers"] },
        { icon: "globe-2", title: "Landing", text: "Mini site for traffic, trust and requests.", items: ["portfolio", "reviews", "map and contacts", "analytics"] },
      ],
      demoSteps: [
        { title: "Choose a service", text: "Client starts with a clear list of services.", image: "" },
        { title: "Choose a date", text: "Only available days and slots are shown.", image: "" },
        { title: "Confirmation", text: "Admin gets the request, client gets a reminder.", image: "" },
      ],
      cta: { title: "Need a bot and landing for your business?", text: "We launch the base version quickly, then expand it around your process.", discuss: "Discuss project", watch: "Watch demo" },
      pricingBlock: {
        title: "Pricing",
        text:
          "The price depends on the niche, languages, design and booking logic. You can discuss the base package in Telegram.",
      },
      faqBlock: {
        title: "FAQ",
        items: [
          {
            question: "Does the landing page need a backend?",
            answer: "No. The landing page remains static and can be hosted on GitHub Pages.",
          },
          {
            question: "Can the nail demo be replaced?",
            answer:
              "Yes. Services, texts, visual style and booking flow can be changed for your niche.",
          },
        ],
      },
      footer: {
        subtitle: "Telegram booking bot + landing page",
        contacts: { telegram: "Telegram: @jxx15", location: "Belgrade, Serbia" },
        copyright: "© 2026 SlotBot. All rights reserved.",
        columns: [
          { title: "Product", links: ["Features", "How it works", "Pricing", "Demo"] },
          { title: "Company", links: ["About", "Cases", "Blog", "Contacts"] },
          { title: "Support", links: ["FAQ", "Docs", "Contact us"] },
        ],
      },
      mockup: {
        phoneTitle: "SlotBot",
        stepLabel: "Step",
        flow: ["Choose service", "Choose date", "Choose time", "Booking confirmation"],
        landingLabel: "Landing + bot",
        landingCta: "Book online",
        map: "Map near contacts",
      },
    },
    sr: {
      title: "SlotBot | Telegram bot za zakazivanje",
      metaDescription:
        "Demo proizvoda: Telegram bot za zakazivanje + mini landing stranica za usluzne biznise.",
      botFeatures: "Funkcije bota",
      featureBack: "Nazad na landing",
      featureBadgeBot: "Booking bot",
      featureBadgeWebsite: "Landing page",
      featureBadgeSetup: "Custom setup",
      featureHeroTitle: "Sta se moze dodati u bot i landing",
      featureHeroText:
        "Osnovni paket brzo pokrece zakazivanje. Dodatne funkcije se dodaju prema realnom procesu biznisa.",
      featureDemoTitle: "Demo zakazivanja",
      featureDemoSubtitle: "Scenario se moze prilagoditi svakoj nisi",
      demoVideoTitle: "Demo video",
      demoVideoText: "Kratak video proizvoda",
      upgradeTitle: "Opcije prosirenja",
      upgradeSubtitle: "Birajte samo ono sto je korisno za posao",
      packageTitle: "Kako koristiti demo",
      packageText:
        "Prikazite trenutni tok, izaberite korisne blokove, pa prilagodite tekstove, usluge, dizajn i logiku zakazivanja.",
      discussCustom: "Dogovori implementaciju",
      footerNote:
        "SlotBot je primer paketa: Telegram bot za zakazivanje + landing page. Dizajn i tok se prilagodjavaju po nisi.",
      nav: { features: "Mogucnosti", how: "Kako radi", useCases: "Za koga", pricing: "Cene", faq: "FAQ" },
      sectionTitles: {
        clientBenefits: "Sta klijent dobija",
        workflow: "Kako radi",
        ownerBenefits: "Zasto je korisno vlasniku",
        useCases: "Pogodno za",
        businessFeatures: "Funkcije za biznis",
      },
      hero: {
        badge: "Demo primer: zakazivanje kod nail mastera",
        title: "Telegram bot za zakazivanje + mini sajt za nove upite",
        text:
          "Klijent vidi usluge, cene i slobodne termine, zatim zakazuje kroz Telegram. Radi ne samo za nail mastere, vec za svaki posao sa terminima ili rezervacijama.",
        primaryCta: "Probaj Telegram demo",
        secondaryCta: "Za vlasnike biznisa",
        trust: ["RU / EN / SR", "Obavestenja", "Podsetnici", "Poruke"],
      },
      clientBenefits: [
        { icon: "tag", title: "Usluge i cene", text: "Jasno je sta postoji i koliko kosta." },
        { icon: "calendar-days", title: "Slobodni termini", text: "Klijent bira realne slobodne termine." },
        { icon: "zap", title: "Zakazivanje za 1 minut", text: "Brz izbor i potvrda bez viska koraka." },
        { icon: "bell", title: "Podsetnik za termin", text: "Klijent dobija podsetnik unapred." },
      ],
      workflowSteps: ["Covek dolazi na landing", "Klikne zakazi", "Prelazi u Telegram bot", "Bira uslugu, datum i vreme"],
      workflowNote: "Majstor ili administrator dobija novu rezervaciju bez rucnog dopisivanja.",
      videoDemo: {
        title: "Video demonstracija",
        text:
          "Pokazite klijentu ili vlasniku biznisa kako izgleda put od landing stranice do zakazivanja u Telegramu.",
        fallback: "Ako se video ne ucita, proverite mp4 putanju u config.js.",
      },
      ownerBenefits: [
        { icon: "messages-square", title: "Manje rucnog dopisivanja", text: "Zakazivanje je automatizovano u Telegramu." },
        { icon: "inbox", title: "Manje propustenih upita", text: "Ne gubite klijente zbog kasnog odgovora." },
        { icon: "calendar-check", title: "Jasan raspored", text: "Sva zakazivanja su na jednom mestu." },
        { icon: "bell-ring", title: "Podsetnici klijentima", text: "Manje kasnjenja i nedolazaka." },
        { icon: "heart", title: "Povratak klijenata", text: "Lako ponovno zakazivanje vraca klijente." },
        { icon: "paintbrush", title: "Prilagodjavanje nisi", text: "Bot i sajt se prilagodjavaju vasem stilu." },
      ],
      useCases: ["Manikir", "Berber", "Masaza", "Kozmetologija", "Joga i casovi", "Radionice", "Mali dogadjaji", "Klinike", "Zubar", "Auto servis"],
      useCasesNote: "Nokti su samo jedan primer upotrebe.",
      nicheShowcase: {
        badge: "Demo varijante",
        title: "Jedan bot. Razliciti biznisi.",
        text:
          "Logika zakazivanja ostaje ista, a landing se menja prema nisi: usluge, cene, adresa, fotografije, jezik i tekstovi.",
        imageAlt:
          "SlotBot prikaz demo nisa: Telegram bot i mini landing stranice za razlicite usluzne biznise",
        cta: "Pogledaj demo",
        soon: "Uskoro",
        demos: [
          { title: "Beauty / Nail", href: "./demo/beauty/index.html", status: "ready" },
          { title: "Berber", href: "./demo/barber/index.html", status: "ready" },
          { title: "Masaza", href: "./demo/massage/index.html", status: "ready" },
          { title: "Casovi", href: "./demo/classes/index.html", status: "ready" },
          { title: "Dogadjaji", href: "./demo/events/index.html", status: "ready" },
          { title: "Klinika", href: "./demo/clinic/index.html", status: "ready" },
          { title: "Zubar", href: "./demo/dentist/index.html", status: "ready" },
          { title: "Auto servis", href: "./demo/car-service/index.html", status: "ready" },
        ],
      },
      demoCase: {
        title: "Primer primene: sajt nail mastera",
        name: "Anna • Nail Master",
        intro: "Idealan manikir za sigurnost svakog dana",
        badge: "Beauty / Nail demo",
        openPageCta: "Otvori demo stranicu",
        bookCta: "Zakazi",
        servicesTitle: "Usluge i cene",
        reviewsTitle: "Recenzije klijenata",
        locationTitle: "Gde radim",
        review: "Veoma zadovoljna! Uredno, lepo i brzo. Dolazim ponovo.",
        location: "Beograd, Srbija",
        services: [
          { name: "Klasicni manikir", price: "1 800 RSD" },
          { name: "Manikir + gel lak", price: "2 300 RSD" },
          { name: "Ojacavanje noktiju", price: "500 RSD" },
          { name: "Dizajn noktiju", price: "od 200 RSD" },
        ],
        checklistTitle: "Demo primer ukljucuje:",
        checklist: ["Portfolio", "Usluge i cene", "Mapa", "Dugme za zakazivanje", "WhatsApp / Instagram / Telegram kontakt"],
        calloutTitle: "Ovaj scenario se lako prilagodjava drugoj nisi",
        calloutText: "Menjamo dizajn, usluge i tekstove za vas biznis.",
      },
      featureGroups: [
        { icon: "calendar-days", title: "Tok zakazivanja", text: "Put klijenta od usluge do potvrde.", items: ["izbor usluge", "datum i vreme", "potvrda", "podsetnici"] },
        { icon: "user-round", title: "Admin panel", text: "Upravljanje zakazivanjem i klijentima.", items: ["obavestenja", "lista zakazivanja", "pomeranje i otkazivanje", "upravljanje klijentima"] },
        { icon: "megaphone", title: "Marketing", text: "Alati koji pomazu da se klijenti vrate.", items: ["promo kodovi", "slanje poruka", "slobodni termini", "akcije i ponude"] },
        { icon: "globe-2", title: "Mini sajt", text: "Mini sajt za saobracaj, poverenje i upite.", items: ["portfolio", "recenzije", "mapa i kontakti", "analitika"] },
      ],
      demoSteps: [
        { title: "Izaberi uslugu", text: "Klijent krece od jasne liste usluga.", image: "" },
        { title: "Izaberi datum", text: "Prikazuju se samo dostupni dani i termini.", image: "" },
        { title: "Potvrda", text: "Admin dobija upit, klijent dobija podsetnik.", image: "" },
      ],
      cta: { title: "Treba vam ovakav bot i landing?", text: "Osnovnu verziju pravimo brzo, zatim je sirimo prema vasem procesu.", discuss: "Dogovori projekat", watch: "Pogledaj demo" },
      pricingBlock: {
        title: "Cene",
        text:
          "Cena zavisi od nise, jezika, dizajna i potrebne logike zakazivanja. Osnovni paket mozete dogovoriti u Telegramu.",
      },
      faqBlock: {
        title: "FAQ",
        items: [
          {
            question: "Da li je potreban backend za landing?",
            answer: "Ne. Landing ostaje staticki i moze da radi na GitHub Pages.",
          },
          {
            question: "Da li nail primer moze da se zameni?",
            answer:
              "Da. Usluge, tekstovi, vizuelni stil i tok zakazivanja menjaju se prema vasoj nisi.",
          },
        ],
      },
      footer: {
        subtitle: "Telegram booking bot + landing page",
        contacts: { telegram: "Telegram: @jxx15", location: "Beograd, Srbija" },
        copyright: "© 2026 SlotBot. Sva prava zadrzana.",
        columns: [
          { title: "Proizvod", links: ["Mogucnosti", "Kako radi", "Cene", "Demo"] },
          { title: "Kompanija", links: ["O nama", "Primeri", "Blog", "Kontakti"] },
          { title: "Podrska", links: ["FAQ", "Dokumentacija", "Kontakt"] },
        ],
      },
      mockup: {
        phoneTitle: "SlotBot",
        stepLabel: "Korak",
        flow: ["Izaberite uslugu", "Izaberite datum", "Izaberite vreme", "Potvrda zakazivanja"],
        landingLabel: "Sajt + bot",
        landingCta: "Zakazi online",
        map: "Mapa pored kontakata",
      },
    },
  },
};
