window.MASTER_PROFILE = {
  defaultLanguage: "en",
  supportedLanguages: [
    { code: "sr", label: "SR" },
    { code: "en", label: "EN" },
    { code: "ru", label: "RU" },
  ],
  masterName: "Anna Nails",
  city: "Novi Sad",
  area: "Bulevar oslobodjenja",
  bookingUrl: "https://t.me/Beauty_Master_name_bot",
  telegramUrl: "https://t.me/Beauty_Master_name_bot",
  viberUrl: "viber://chat?number=%2B381601234567",
  whatsappUrl: "https://wa.me/381601234567",
  instagramUrl: "https://www.instagram.com/",
  portfolioUrl: "https://ru.pinterest.com/search/pins/?q=nail%20design&rs=typed",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Bulevar%20oslobodjenja%20119%2C%2021000%2C%20Novi%20Sad%2C%20Serbia",
  mapEmbedUrl:
    "https://maps.google.com/maps?q=Bulevar%20oslobodjenja%20119%2C%2021000%2C%20Novi%20Sad%2C%20Serbia&output=embed",
  address: "Булевар ослобођења 119, 21000, Нови Сад",
  languages: "RU / SR / EN",
  currency: "RSD",
  heroImage:
    "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1800&q=85",
  demoVideo: "",
  demoPoster: "",
  creatorName: "Created by Dun4ev",
  creatorUrl: "https://t.me/jxx15",
  i18n: {
    en: {
      title: "Anna Nails | Online Booking",
      demoLabel: "Demo page",
      demoNote: "Example website and Telegram booking bot included as a demo package.",
      onlineBooking: "Online booking",
      tagline: "Manicure, gel polish and clean everyday nails",
      bookOnline: "Book online",
      portfolio: "Portfolio",
      botFeatures: "Bot features",
      servicesTitle: "Services",
      pricesIn: "Prices in RSD",
      demoTitle: "How booking works",
      demoSubtitle: "Short demo for clients and masters",
      demoVideoTitle: "Demo video",
      demoVideoText: "Add a short vertical video to landing/assets",
      locationTitle: "Location",
      openMap: "Open in Google Maps",
      mapFallback: "Open Google Maps",
      footerNote:
        "This page is an example design included with the booking bot. A custom visual design can be discussed separately.",
      featureBack: "Back to demo",
      featureBadgeBot: "Booking bot",
      featureBadgeWebsite: "Website add-ons",
      featureBadgeSetup: "Custom setup",
      featureHeroTitle: "What can be added to the bot",
      featureHeroText:
        "The current page is a demo package: landing page plus Telegram booking bot. Extra features can be added step by step depending on the master's workflow.",
      featureDemoTitle: "Demo first",
      featureDemoSubtitle: "Same booking flow, shown separately for discussion",
      upgradeTitle: "Upgrade options",
      upgradeSubtitle: "Choose only what is useful for the business",
      packageTitle: "How to use this demo",
      packageText:
        "The basic bot can be launched quickly. Additional functions, design changes, languages and analytics are discussed separately after the workflow is clear.",
      discussCustom: "Discuss custom version",
      demoSteps: [
        {
          title: "Choose a date",
          text: "Client opens the bot and sees only available days.",
          image: "",
        },
        {
          title: "Pick a time",
          text: "Busy slots disappear automatically after booking.",
          image: "",
        },
        {
          title: "Admin gets booking",
          text: "Master receives client name, phone and appointment time.",
          image: "",
        },
      ],
      featureGroups: [
        {
          title: "Booking flow",
          text: "Make client booking more precise and useful for the master.",
          items: [
            "Service selection before date and time",
            "Different duration for each service",
            "Reschedule appointment without cancelling",
            "Client comments before confirmation",
          ],
        },
        {
          title: "Admin tools",
          text: "Reduce manual work and make schedule management faster.",
          items: [
            "Monthly schedule templates",
            "Auto-create slots for selected weekdays",
            "Morning list of today's bookings",
            "Client no-show / completed visit status",
          ],
        },
        {
          title: "Marketing",
          text: "Help the master bring clients back and promote free windows.",
          items: [
            "Broadcast messages to clients",
            "Promo codes and first-visit discount",
            "Birthday reminders",
            "Free-window notifications",
          ],
        },
        {
          title: "Website",
          text: "Expand the landing page into a stronger online profile.",
          items: [
            "Custom visual design",
            "Photo gallery and works",
            "RU / SR / EN versions",
            "Analytics for button clicks and bookings",
          ],
        },
      ],
      services: [
        { name: "Classic manicure", price: "2 000 RSD", time: "60 min" },
        { name: "Combined manicure", price: "2 400 RSD", time: "70 min" },
        { name: "Gel polish", price: "3 000 RSD", time: "90 min" },
        { name: "Manicure + gel polish", price: "4 200 RSD", time: "120 min" },
        { name: "French design", price: "+800 RSD", time: "+20 min" },
        { name: "Simple nail design", price: "300-900 RSD", time: "+15 min" },
        { name: "Strengthening", price: "1 000 RSD", time: "+20 min" },
        { name: "Removal", price: "800 RSD", time: "30 min" },
        { name: "Nail repair", price: "300 RSD", time: "15 min" },
        { name: "Pedicure", price: "3 500 RSD", time: "90 min" },
      ],
    },
    sr: {
      title: "Anna Nails | Online zakazivanje",
      demoLabel: "Demo stranica",
      demoNote: "Primer sajta i Telegram bota za zakazivanje u demo paketu.",
      onlineBooking: "Online zakazivanje",
      tagline: "Manikir, gel lak i uredni nokti za svaki dan",
      bookOnline: "Zakaži termin",
      portfolio: "Portfolio",
      botFeatures: "Funkcije bota",
      servicesTitle: "Usluge",
      pricesIn: "Cene u RSD",
      demoTitle: "Kako funkcioniše zakazivanje",
      demoSubtitle: "Kratak demo za klijente i majstore",
      demoVideoTitle: "Demo video",
      demoVideoText: "Dodajte kratak vertikalni video u landing/assets",
      locationTitle: "Lokacija",
      openMap: "Otvori u Google Maps",
      mapFallback: "Otvori Google Maps",
      footerNote:
        "Ova stranica je primer dizajna koji ide uz bot za zakazivanje. Poseban vizuelni dizajn može se dogovoriti odvojeno.",
      featureBack: "Nazad na demo",
      featureBadgeBot: "Bot za zakazivanje",
      featureBadgeWebsite: "Dodaci za sajt",
      featureBadgeSetup: "Podešavanje po meri",
      featureHeroTitle: "Šta se može dodati u bot",
      featureHeroText:
        "Trenutna stranica je demo paket: landing stranica plus Telegram bot za zakazivanje. Dodatne funkcije se mogu dodavati korak po korak prema načinu rada majstora.",
      featureDemoTitle: "Prvo demo",
      featureDemoSubtitle: "Isti tok zakazivanja, prikazan posebno za dogovor",
      upgradeTitle: "Dodatne opcije",
      upgradeSubtitle: "Biraju se samo funkcije koje su korisne za posao",
      packageTitle: "Kako koristiti ovaj demo",
      packageText:
        "Osnovni bot može brzo da se pokrene. Dodatne funkcije, izmene dizajna, jezici i analitika dogovaraju se posebno kada je tok rada jasan.",
      discussCustom: "Dogovori verziju po meri",
      demoSteps: [
        {
          title: "Izbor datuma",
          text: "Klijent otvara bot i vidi samo dostupne dane.",
          image: "",
        },
        {
          title: "Izbor vremena",
          text: "Zauzeti termini automatski nestaju nakon zakazivanja.",
          image: "",
        },
        {
          title: "Majstor dobija rezervaciju",
          text: "Majstor dobija ime klijenta, telefon i vreme termina.",
          image: "",
        },
      ],
      featureGroups: [
        {
          title: "Tok zakazivanja",
          text: "Zakazivanje može biti preciznije i korisnije za majstora.",
          items: [
            "Izbor usluge pre datuma i vremena",
            "Različito trajanje za svaku uslugu",
            "Promena termina bez otkazivanja",
            "Komentar klijenta pre potvrde",
          ],
        },
        {
          title: "Admin alati",
          text: "Manje ručnog rada i brže upravljanje rasporedom.",
          items: [
            "Mesečni šabloni rasporeda",
            "Automatsko kreiranje termina za izabrane dane",
            "Jutarnji spisak današnjih zakazivanja",
            "Status: došao / nije došao / završeno",
          ],
        },
        {
          title: "Marketing",
          text: "Pomaže majstoru da vraća klijente i promoviše slobodne termine.",
          items: [
            "Slanje poruka klijentima",
            "Promo kodovi i popust za prvi dolazak",
            "Podsetnici za rođendan",
            "Obaveštenja o slobodnim terminima",
          ],
        },
        {
          title: "Sajt",
          text: "Landing stranica može postati jači online profil.",
          items: [
            "Vizuelni dizajn po meri",
            "Foto galerija radova",
            "RU / SR / EN verzije",
            "Analitika klikova i zakazivanja",
          ],
        },
      ],
      services: [
        { name: "Klasičan manikir", price: "2 000 RSD", time: "60 min" },
        { name: "Kombinovani manikir", price: "2 400 RSD", time: "70 min" },
        { name: "Gel lak", price: "3 000 RSD", time: "90 min" },
        { name: "Manikir + gel lak", price: "4 200 RSD", time: "120 min" },
        { name: "French dizajn", price: "+800 RSD", time: "+20 min" },
        { name: "Jednostavan dizajn", price: "300-900 RSD", time: "+15 min" },
        { name: "Ojačavanje noktiju", price: "1 000 RSD", time: "+20 min" },
        { name: "Skidanje materijala", price: "800 RSD", time: "30 min" },
        { name: "Popravka nokta", price: "300 RSD", time: "15 min" },
        { name: "Pedikir", price: "3 500 RSD", time: "90 min" },
      ],
    },
    ru: {
      title: "Anna Nails | Онлайн-запись",
      demoLabel: "Тестовая страница",
      demoNote: "Пример сайта и Telegram-бота для записи, который идет как демо-пакет.",
      onlineBooking: "Онлайн-запись",
      tagline: "Маникюр, гель-лак и аккуратные ногти на каждый день",
      bookOnline: "Записаться",
      portfolio: "Портфолио",
      botFeatures: "Функции бота",
      servicesTitle: "Услуги",
      pricesIn: "Цены в RSD",
      demoTitle: "Как работает запись",
      demoSubtitle: "Короткое демо для клиентов и мастеров",
      demoVideoTitle: "Демо-видео",
      demoVideoText: "Добавьте короткое вертикальное видео в landing/assets",
      locationTitle: "Адрес",
      openMap: "Открыть в Google Maps",
      mapFallback: "Открыть Google Maps",
      footerNote:
        "Эта страница — пример оформления сайта, который идёт как приложение к боту записи. Индивидуальный дизайн можно обсудить отдельно.",
      featureBack: "Назад к демо",
      featureBadgeBot: "Бот записи",
      featureBadgeWebsite: "Дополнения сайта",
      featureBadgeSetup: "Настройка под ключ",
      featureHeroTitle: "Что можно добавить в бота",
      featureHeroText:
        "Текущая страница — демо-пакет: лендинг плюс Telegram-бот для записи. Дополнительные функции можно добавлять поэтапно под реальный процесс мастера.",
      featureDemoTitle: "Сначала демо",
      featureDemoSubtitle: "Тот же сценарий записи, отдельно для обсуждения",
      upgradeTitle: "Дополнительные опции",
      upgradeSubtitle: "Выбираем только то, что полезно бизнесу",
      packageTitle: "Как использовать это демо",
      packageText:
        "Базового бота можно запустить быстро. Дополнительные функции, изменения дизайна, языки и аналитика обсуждаются отдельно после понимания рабочего процесса.",
      discussCustom: "Обсудить версию под себя",
      demoSteps: [
        {
          title: "Выбор даты",
          text: "Клиент открывает бота и видит только доступные дни.",
          image: "",
        },
        {
          title: "Выбор времени",
          text: "Занятые слоты автоматически исчезают после записи.",
          image: "",
        },
        {
          title: "Админ получает запись",
          text: "Мастер получает имя клиента, телефон и время визита.",
          image: "",
        },
      ],
      featureGroups: [
        {
          title: "Сценарий записи",
          text: "Запись можно сделать точнее и полезнее для мастера.",
          items: [
            "Выбор услуги перед датой и временем",
            "Разная длительность для каждой услуги",
            "Перенос записи без отмены",
            "Комментарий клиента перед подтверждением",
          ],
        },
        {
          title: "Инструменты админа",
          text: "Меньше ручной работы и быстрее управление расписанием.",
          items: [
            "Шаблоны расписания на месяц",
            "Автосоздание слотов по выбранным дням недели",
            "Утренний список записей на сегодня",
            "Статус визита: пришёл / не пришёл / завершено",
          ],
        },
        {
          title: "Маркетинг",
          text: "Помогает возвращать клиентов и продвигать свободные окна.",
          items: [
            "Рассылки клиентам",
            "Промокоды и скидка на первый визит",
            "Напоминания о днях рождения",
            "Уведомления о свободных окнах",
          ],
        },
        {
          title: "Сайт",
          text: "Лендинг можно расширить до полноценного онлайн-профиля.",
          items: [
            "Индивидуальный визуальный дизайн",
            "Фотогалерея работ",
            "RU / SR / EN версии",
            "Аналитика кликов и записей",
          ],
        },
      ],
      services: [
        { name: "Классический маникюр", price: "2 000 RSD", time: "60 мин" },
        { name: "Комбинированный маникюр", price: "2 400 RSD", time: "70 мин" },
        { name: "Гель-лак", price: "3 000 RSD", time: "90 мин" },
        { name: "Маникюр + гель-лак", price: "4 200 RSD", time: "120 мин" },
        { name: "Френч-дизайн", price: "+800 RSD", time: "+20 мин" },
        { name: "Простой дизайн", price: "300-900 RSD", time: "+15 мин" },
        { name: "Укрепление", price: "1 000 RSD", time: "+20 мин" },
        { name: "Снятие покрытия", price: "800 RSD", time: "30 мин" },
        { name: "Ремонт ногтя", price: "300 RSD", time: "15 мин" },
        { name: "Педикюр", price: "3 500 RSD", time: "90 мин" },
      ],
    },
  },
};
